# Generated by Django 3.0.7 on 2020-07-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200709_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_uid',
            new_name='blah',
        ),
    ]
