# Generated by Django 3.0.7 on 2020-07-09 15:33

from django.db import migrations
import styleguide_example.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20200709_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blah',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=styleguide_example.common.fields.UidField(blank=True, max_length=28, primary_key=True, serialize=False),
        ),
    ]
