# Generated by Django 3.0.7 on 2020-07-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_profile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
