# Generated by Django 3.0.7 on 2020-07-10 10:58

from django.db import migrations
import styleguide_example.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20200710_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=styleguide_example.common.fields.UidField(default='Ul1SAhu4CDONAo7ZnYfEhIYNtTEN', max_length=28),
        ),
    ]
