# Generated by Django 3.0.7 on 2020-07-10 11:07

from django.db import migrations
import styleguide_example.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20200710_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=styleguide_example.common.fields.UidField(default='RpRkQIyDyeNE2p2bIpJalPiJV7z9', max_length=28),
        ),
    ]
