# Generated by Django 3.0.7 on 2020-07-10 11:43

from django.db import migrations
import styleguide_example.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20200710_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=styleguide_example.common.fields.UidField(default='ezDvsuFwkoWhps5enFeMmy0YGjE8', max_length=28),
        ),
    ]
