# Generated by Django 4.1.3 on 2022-11-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_randommodel_start_date_before_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='randommodel',
            name='start_date_before_end_date',
        ),
        migrations.AddConstraint(
            model_name='randommodel',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='start_date_before_end_date'),
        ),
    ]
