# Generated by Django 4.1.3 on 2023-01-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_simplemodel_randommodel_simple_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='simplemodel',
            name='updated_at',
        ),
    ]
