# Generated by Django 3.2.10 on 2021-12-20 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_baseuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='jwt_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
